#!/bin/sh

set -o errexit
set -o nounset

printf "\n"
printf "################################\n"
printf "#   Instalando dependências    #\n"
printf "################################\n"
printf "\n\n"

npm install

printf "\n"
printf "##############################\n"
printf "#   Variáveis de ambiente    #\n"
printf "##############################\n"
printf "\n\n"

export $(grep -v '^#' .envs/.local/server.env | xargs)
cat .envs/.local/server.env

printf "\n"
printf "#########################\n"
printf "#  Inicializando o TOR  #\n"
printf "#########################\n"
printf "\n\n"

sudo -u pptruser tor &

printf "\n\n"
printf "###########################\n"
printf "# Compilando e executando #\n"
printf "###########################\n"
printf "\n"

npm run serve
